# Site settings
title: Gonzalo Bulnes Guilpain's Blog
description: > # this means to ignore newlines until "baseurl:"
  Gonzalo Bulnes Guilpain's blog.
author: Gonzalo Bulnes Guilpain
baseurl: "" # the subpath of your site, e.g. /blog/
tagsurl: "/tags/"
url: "https://gonzalo-bulnes.github.io"
license: 'All rights reserved.'

# Build settings
exclude: ['Gemfile', 'README', 'bower.json']
markdown: kramdown
