# Site settings
title: Gonzalo Bulnes Guilpain
description: > # this means to ignore newlines until "baseurl:"
  Gonzalo Bulnes Guilpain's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gonzalo-bulnes.github.io"
github_username:  gonzalo-bulnes
leanpub_username: gonzalo-bulnes

# Build settings
exclude: ['Gemfile', 'README', 'bower.json']
markdown: kramdown
