author:
  name: Gonzalo Bulnes Guilpain
  github: https://github.com/gonzalo-bulnes
comments:
  issue:
    base_url: https://github.com/gonzalo-bulnes/gonzalo-bulnes.github.io/issues
    api_base_url: https://api.github.com/repos/gonzalo-bulnes/gonzalo-bulnes.github.io/issues
exclude: [Gemfile, Gemfile.lock, README.md]
github: https://github.com/gonzalo-bulnes/gonzalo-bulnes.github.io
markdown: redcarpet
pygments: true
url: http://gonzalobulnes.com
